{{- if .Release.IsUpgrade -}} # Should not be applied on install, because it depends on CRDs

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-privkey
    solvers:
      # - http01:
      #     ingress:
      #       class: traefik
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: token

{{- end -}}
