prometheus:
  serverFiles:
    prometheus.yml:
      rule_files: []

  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 24Mi
      limits:
        cpu: 50m
        memory: 48Mi

  prometheus-node-exporter:
    enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 12Mi
      limits:
        cpu: 25m
        memory: 24Mi

  configmapReload:
    prometheus:
      enabled: false

  server:
    revisionHistoryLimit: 1

    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 10s

    persistentVolume:
      enabled: false

    remoteWrite: [] # Should be set to the URL of the Prometheus server that will receive the data from this agent

    defaultFlagsOverride:
      - --agent
      - --config.file=/etc/config/prometheus.yml
      - --storage.agent.wal-compression
      - --storage.agent.retention.max-time=30m
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

