prometheus:
  serverFiles:
    prometheus.yml:
      rule_files: []
      scrape_configs:
        - job_name: kubernetes-api-servers
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: default;kubernetes;https
              source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

        - job_name: kubernetes-nodes
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true

        - job_name: kubernetes-nodes-cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          metrics_path: /metrics/cadvisor
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - source_labels: [__metrics_path__]
              target_label: metrics_path
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: >-
                container_cpu_(usage_seconds_total|cfs_periods_total|cfs_throttled_periods_total)|
                container_memory_(working_set_bytes|usage_bytes|rss|cache|swap)|
                container_network_(receive|transmit)_(bytes|packets_dropped)_total|
                container_fs_(usage|limit|reads_bytes|writes_bytes).*|
                container_(start_time_seconds|oom_events_total|spec_memory_limit_bytes|spec_cpu_quota|spec_cpu_period)|
                machine_(cpu_cores|memory_bytes)
              action: keep

        - job_name: kubernetes-pods
          honor_labels: true
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            - action: drop
              regex: "true"
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
            - action: replace
              regex: (https?)
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              target_label: __metrics_path__
            - action: replace
              regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
              replacement: "[$2]:$1"
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              target_label: __address__
            - action: replace
              regex: (\d+);((([0-9]+?)(\.|$)){4})
              replacement: $2:$1
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - action: replace
              source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - action: drop
              regex: Pending|Succeeded|Failed|Completed
              source_labels: [__meta_kubernetes_pod_phase]
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

        - job_name: kubernetes-pods-slow
          honor_labels: true
          scrape_interval: 5m
          scrape_timeout: 30s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
            - action: replace
              regex: (https?)
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              target_label: __metrics_path__
            - action: replace
              regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
              replacement: "[$2]:$1"
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              target_label: __address__
            - action: replace
              regex: (\d+);((([0-9]+?)(\.|$)){4})
              replacement: $2:$1
              source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - action: replace
              source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - action: drop
              regex: Pending|Succeeded|Failed|Completed
              source_labels: [__meta_kubernetes_pod_phase]
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

        - job_name: kubernetes-service-endpoints
          honor_labels: true
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            - action: drop
              regex: "true"
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
            - action: replace
              regex: (https?)
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              target_label: __metrics_path__
            - action: replace
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - action: replace
              source_labels: [__meta_kubernetes_service_name]
              target_label: service
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

        - job_name: kubernetes-service-endpoints-slow
          honor_labels: true
          scrape_interval: 5m
          scrape_timeout: 30s
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
            - action: replace
              regex: (https?)
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              target_label: __metrics_path__
            - action: replace
              regex: (.+?)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - action: replace
              source_labels: [__meta_kubernetes_service_name]
              target_label: service
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

        - job_name: kubernetes-services
          honor_labels: true
          kubernetes_sd_configs:
            - role: service
          metrics_path: /probe
          params:
            module: [http_2xx]
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
            - source_labels: [__address__]
              target_label: __param_target
            - replacement: blackbox
              target_label: __address__
            - source_labels: [__param_target]
              target_label: instance
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_service_name]
              target_label: service

        - job_name: prometheus
          static_configs:
            - targets: [localhost:9090]

        - job_name: prometheus-pushgateway
          honor_labels: true
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - action: keep
              regex: pushgateway
              source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]

  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  kube-state-metrics:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 25m
        memory: 96Mi

  prometheus-node-exporter:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 25m
        memory: 48Mi

  prometheus-pushgateway:
    enabled: true

  configmapReload:
    prometheus:
      enabled: false

  server:
    revisionHistoryLimit: 1

    global:
      scrape_interval: 60s
      scrape_timeout: 10s
      evaluation_interval: 60s

    persistentVolume:
      enabled: false

    remoteWrite: [] # Should be set to the URL of the Prometheus server that will receive the data from this agent

    defaultFlagsOverride:
      - --agent
      - --config.file=/etc/config/prometheus.yml
      - --storage.agent.wal-compression
      - --storage.agent.retention.max-time=15m
      - --storage.agent.wal-truncate-frequency=5m
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle

    env:
      - name: GOGC
        value: "75"
      - name: GOMEMLIMIT
        value: "110MiB"

    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi