apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
spec:
  secretName: linkerd-identity-issuer
  duration: 336h
  renewBefore: 168h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.{{ .Release.Namespace }}.cluster.local
  dnsNames:
    - identity.{{ .Release.Namespace }}.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth