apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: viz-ipallowlist
spec:
  ipAllowList:
    sourceRange:
    {{- range (.Values.allowedIps | split ",") }}
      - {{ . }}
    {{- end }}
