{{- range .Values.backup.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo-credentials
  namespace: {{ . }}
stringData:
  userUsername: {{ $.Values.backup.repo.username | quote }}
  userPassword: {{ $.Values.backup.repo.password | quote }}
  repoPassword: {{ $.Values.backup.repo.encryptionKey | quote }}
{{- end }}
