metrics-server:
  args:
    - --kubelet-insecure-tls
  revisionHistoryLimit: 2
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 128Mi
