metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  resources:
    requests:
      cpu: 10m
      memory: 48Mi
    limits:
      cpu: 25m
      memory: 64Mi
