apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: "7.6.10"
    repository: "https://argoproj.github.io/argo-helm"
  - name: argo-rollouts
    version: "2.37.7"
    repository: "https://argoproj.github.io/argo-helm"
  - name: argocd-image-updater
    version: "0.11.0"
    repository: "https://argoproj.github.io/argo-helm"
