apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: "9.4.1"
    repository: "https://argoproj.github.io/argo-helm"
  - name: argo-rollouts
    version: "2.40.5"
    repository: "https://argoproj.github.io/argo-helm"
  - name: argocd-image-updater
    version: "1.1.0"
    repository: "https://argoproj.github.io/argo-helm"