apiVersion: v2
name: certmanager
description: Cert-Manager Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: cert-manager
    version: "v1.19.3"
    repository: "https://charts.jetstack.io"