apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.prometheus.server.ingressRoute.hostname }}-tls
spec:
  secretName: {{ .Values.prometheus.server.ingressRoute.hostname }}-tls
  dnsNames:
    - {{ .Values.prometheus.server.ingressRoute.hostname }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
